#!/usr/bin/env python3
"""
Regenerate the drift-prone reference pages of the OVOS technical manual from
their sources of truth: gh-automations reusable workflows, ovos-config's
bundled mycroft.conf, and installed OVOS console scripts.

Only the content between matching
    <!-- BEGIN GENERATED: <id> -->
    <!-- END GENERATED -->
marker pairs is touched. Everything else in the target pages (intros, usage
examples, behavior notes, jobs tables, etc.) is hand-written prose and is
left untouched.

Usage:
    python3 tools/gen_reference.py workflows [--repo-path PATH]
    python3 tools/gen_reference.py config
    python3 tools/gen_reference.py cli [--venv-bin PATH]
    python3 tools/gen_reference.py all

Requires: PyYAML (`pip install pyyaml`), run with any Python that has it
(the project's docs venv works fine).
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"

GEN_BEGIN = "<!-- BEGIN GENERATED: {id} -->"
GEN_END = "<!-- END GENERATED -->"
GEN_NOTE = (
    "<!-- This section is auto-generated by tools/gen_reference.py from the "
    "upstream source of truth. Do not hand-edit; re-run the script instead. -->"
)


def wrap(section_id: str, body: str) -> str:
    return f"{GEN_BEGIN.format(id=section_id)}\n{GEN_NOTE}\n{body.rstrip()}\n{GEN_END}"


def replace_marked_section(text: str, section_id: str, new_body: str) -> tuple[str, bool]:
    """Replace the content between BEGIN/END markers for `section_id`.

    Returns (new_text, found). If the markers don't exist yet, returns the
    text unchanged with found=False so the caller can insert them.
    """
    begin = re.escape(GEN_BEGIN.format(id=section_id))
    pattern = re.compile(begin + r".*?" + re.escape(GEN_END), re.DOTALL)
    replacement = wrap(section_id, new_body)
    if pattern.search(text):
        return pattern.sub(lambda _m: replacement, text, count=1), True
    return text, False


# ---------------------------------------------------------------------------
# a) gh-automations reusable workflow reference
# ---------------------------------------------------------------------------

def _md_escape(val) -> str:
    if val is None:
        return ""
    s = str(val)
    return s.replace("|", "\\|").replace("\n", " ").strip()


def _fmt_default(inp: dict) -> str:
    if "default" not in inp:
        return "_(required)_" if inp.get("required") else ""
    d = inp["default"]
    if isinstance(d, bool):
        d = str(d).lower()
    if d == "":
        return '`""`'
    return f"`{d}`"


SECRET_USE_RE = re.compile(r"secrets\.([A-Z][A-Z0-9_]*)\b")


def find_undeclared_secrets(raw_yaml_text: str, declared: dict) -> dict:
    """Some workflows reference `secrets.X` without a formal workflow_call.secrets
    declaration (relying on `secrets: inherit` from the caller). Surface those
    too, so the doc doesn't silently lose them."""
    found = {}
    for name in sorted(set(SECRET_USE_RE.findall(raw_yaml_text))):
        if name in ("GITHUB_TOKEN",) or name in declared:
            continue
        found[name] = {"description": "(used via `secrets: inherit`; not formally declared as a workflow_call secret)"}
    return found


def render_workflow_tables(wc: dict, extra_secrets: dict | None = None) -> str:
    parts = []
    inputs = wc.get("inputs") or {}
    if inputs:
        lines = ["### Inputs", "", "| Input | Type | Default | Description |", "|-------|------|---------|-------------|"]
        for name, spec in inputs.items():
            spec = spec or {}
            lines.append(
                f"| `{name}` | {spec.get('type', 'string')} | {_fmt_default(spec)} | {_md_escape(spec.get('description'))} |"
            )
        parts.append("\n".join(lines))

    secrets = dict(wc.get("secrets") or {})
    secrets.update(extra_secrets or {})
    if secrets:
        lines = ["### Secrets", "", "| Secret | Required | Description |", "|--------|----------|-------------|"]
        for name, spec in secrets.items():
            spec = spec or {}
            req = "yes" if spec.get("required") else "no"
            lines.append(f"| `{name}` | {req} | {_md_escape(spec.get('description'))} |")
        parts.append("\n".join(lines))

    outputs = wc.get("outputs") or {}
    if outputs:
        lines = ["### Outputs", "", "| Output | Description |", "|--------|-------------|"]
        for name, spec in outputs.items():
            spec = spec or {}
            lines.append(f"| `{name}` | {_md_escape(spec.get('description'))} |")
        parts.append("\n".join(lines))

    return "\n\n".join(parts)


def load_workflow_call(path: Path) -> dict | None:
    doc = yaml.safe_load(path.read_text())
    on_key = True if True in doc else "on"
    on = doc.get(on_key)
    if not isinstance(on, dict):
        return None
    return on.get("workflow_call")


WORKFLOW_SECTION_RE = re.compile(
    r"(^## `(?P<name>[\w.\-]+\.yml)`.*?\*\*Source:\*\* `\.github/workflows/(?P=name)`\n\n)"
    r"(?P<body>.*?)"
    r"(?=\n### (?!Inputs|Secrets|Outputs)|\n---\n|\Z)",
    re.DOTALL | re.MULTILINE,
)


def gen_workflows(repo_path: str | None) -> None:
    repo = Path(repo_path or Path.home() / "AgentWorkspaces/ovos/gh-automations")
    if not (repo / ".git").exists():
        sys.exit(f"gh-automations clone not found at {repo} (pass --repo-path)")
    subprocess.run(["git", "fetch", "origin", "dev"], cwd=repo, capture_output=True)
    # Prefer the freshly fetched origin/dev; fall back to whatever ref is
    # already checked out (e.g. a CI checkout pinned to ref: dev) so this
    # also works offline / in a shallow CI clone without a remote named origin.
    ref = "origin/dev"
    if subprocess.run(["git", "rev-parse", "--verify", "-q", ref], cwd=repo, capture_output=True).returncode != 0:
        ref = "HEAD"
    # Use the local worktree content updated to origin/dev without mutating the
    # user's checkout: read blobs directly from the fetched ref.
    ls = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", ref, ".github/workflows"],
        cwd=repo, check=True, capture_output=True, text=True,
    ).stdout.splitlines()

    workflow_calls: dict[str, dict] = {}
    raw_contents: dict[str, str] = {}
    for relpath in ls:
        if not relpath.endswith(".yml"):
            continue
        name = Path(relpath).name
        content = subprocess.run(
            ["git", "show", f"{ref}:{relpath}"], cwd=repo, check=True, capture_output=True, text=True,
        ).stdout
        raw_contents[name] = content
        doc = yaml.safe_load(content)
        on_key = True if True in doc else "on"
        on = doc.get(on_key)
        if not isinstance(on, dict):
            continue
        wc = on.get("workflow_call")
        if wc:
            workflow_calls[name] = wc

    page = DOCS / "gh-automations-workflows.md"
    text = page.read_text()

    def _sub(m: re.Match) -> str:
        name = m.group("name")
        wc = workflow_calls.get(name)
        if not wc:
            return m.group(0)  # leave untouched if source workflow not found
        extra_secrets = find_undeclared_secrets(raw_contents.get(name, ""), wc.get("secrets") or {})
        body = render_workflow_tables(wc, extra_secrets)
        return m.group(1) + wrap(f"workflow-io:{name}", body) + "\n"

    new_text, n = WORKFLOW_SECTION_RE.subn(_sub, text)
    page.write_text(new_text)
    documented = {m.group("name") for m in WORKFLOW_SECTION_RE.finditer(text)}
    missing = documented - set(workflow_calls)
    extra = set(workflow_calls) - documented
    print(f"[workflows] regenerated {n} workflow section(s) in {page.relative_to(REPO_ROOT)}")
    if missing:
        print(f"[workflows] WARNING: documented but not found in source: {sorted(missing)}")
    if extra:
        print(f"[workflows] NOTE: reusable workflows in source but undocumented: {sorted(extra)}")


# ---------------------------------------------------------------------------
# b) config reference
# ---------------------------------------------------------------------------

def _strip_jsonc_comments_with_map(text: str):
    """Return (stripped_json_text, {dotted.key.path: description}).

    Walks mycroft.conf line by line, tracking nesting via brace/bracket
    counting on the *stripped* content so we can associate each `//` comment
    block with the key it immediately precedes.
    """
    lines = text.splitlines()
    descriptions: dict[str, str] = {}
    path_stack: list[str] = []
    pending_comment: list[str] = []
    out_lines = []
    key_re = re.compile(r'^\s*"([^"]+)"\s*:\s*(.*)$')

    for raw in lines:
        stripped = raw.strip()
        if stripped.startswith("//"):
            pending_comment.append(stripped.lstrip("/").strip())
            continue
        # strip trailing // comments (best effort, ignores // inside strings)
        line_no_comment = re.sub(r'(?<!:)//.*$', '', raw) if "://" not in raw else raw
        out_lines.append(line_no_comment)

        m = key_re.match(stripped)
        if m and pending_comment:
            key = m.group(1)
            dotted = ".".join(path_stack + [key])
            descriptions[dotted] = " ".join(pending_comment)
        if m:
            rest = m.group(2)
            if rest.startswith("{"):
                path_stack.append(m.group(1))
        elif stripped.startswith("{") and path_stack:
            pass
        if stripped in ("},", "}"):
            if path_stack:
                path_stack.pop()
        pending_comment = []

    stripped_json = "\n".join(out_lines)
    # remove trailing commas which plain json can't handle
    stripped_json = re.sub(r",\s*([}\]])", r"\1", stripped_json)
    return stripped_json, descriptions


def _flatten(d, prefix=""):
    items = []
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict) and v:
            items.extend(_flatten(v, key))
        else:
            items.append((key, v))
    return items


def _fmt_json_value(v) -> str:
    import json
    if isinstance(v, str):
        return f'`"{v}"`' if v else '`""`'
    if isinstance(v, list):
        return "`[]`" if not v else f"`{json.dumps(v)}`"
    if isinstance(v, dict):
        return "`{}`" if not v else "*(object, see below)*"
    if isinstance(v, bool):
        return f"`{str(v).lower()}`"
    return f"`{json.dumps(v)}`"


def gen_config() -> None:
    try:
        from ovos_config.locations import DEFAULT_CONFIG  # type: ignore
    except ImportError:
        sys.exit("ovos-config is not importable in this interpreter; activate ~/.venvs/ovos")

    raw = Path(DEFAULT_CONFIG).read_text()
    stripped, comment_map = _strip_jsonc_comments_with_map(raw)

    try:
        from ovos_utils.json_helper import load_commented_json  # type: ignore
        data = load_commented_json(DEFAULT_CONFIG)
    except Exception:
        import json
        data = json.loads(stripped)

    overrides_path = REPO_ROOT / "tools" / "config_descriptions.yaml"
    overrides = {}
    if overrides_path.exists():
        overrides = yaml.safe_load(overrides_path.read_text()) or {}

    flat = _flatten(data)
    lines = ["| Key | Default | Description |", "|---|---|---|"]
    for key, value in flat:
        desc = overrides.get(key) or comment_map.get(key, "")
        lines.append(f"| `{key}` | {_fmt_json_value(value)} | {_md_escape(desc)} |")
    body = "\n".join(lines)

    page = DOCS / "config-reference.md"
    text = page.read_text()
    new_text, found = replace_marked_section(text, "mycroft-conf-keys", body)
    if not found:
        # First run: append a new marked section right before the trailing
        # "Source code:" line so existing hand-written sections are untouched.
        marker_block = wrap("mycroft-conf-keys", body)
        anchor = "\n---\n\n*Source code:"
        if anchor in text:
            new_text = text.replace(anchor, f"\n---\n\n## All Keys (Generated)\n\n{marker_block}\n{anchor}", 1)
        else:
            new_text = text.rstrip() + f"\n\n## All Keys (Generated)\n\n{marker_block}\n"
    page.write_text(new_text)
    print(f"[config] regenerated mycroft.conf key table ({len(flat)} keys) in {page.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# c) CLI reference
# ---------------------------------------------------------------------------

CLI_COMMAND_RE = re.compile(r"`(ovos-[a-z0-9\-]+)")

# Commands that either launch a long-running daemon/service or open an
# interactive session connected to a *live* messagebus. Their `--help` never
# returns on its own (or worse, actually starts the service) so they are
# deliberately excluded from --help capture, per the "never start long-running
# daemons" ground rule. They stay documented only via the hand-written tables.
UNSAFE_FOR_HELP_CAPTURE = {
    "ovos-core", "ovos-messagebus", "ovos-dinkum-listener", "ovos-audio",
    "ovos-gui-service", "ovos-gui-debug-tui", "ovos-intent-service",
    "ovos-skill-installer", "ovos-ocp-standalone",
    "ovos-listen", "ovos-speak", "ovos-say-to", "ovos-simple-cli",
}


def _capture_help(cmd: str, venv_bin: Path) -> str | None:
    exe = venv_bin / cmd
    if not exe.exists():
        which = subprocess.run(["which", cmd], capture_output=True, text=True)
        if which.returncode != 0:
            return None
        exe = Path(which.stdout.strip())
    try:
        result = subprocess.run(
            [str(exe), "--help"], capture_output=True, text=True, timeout=15,
        )
        out = (result.stdout or "") + (result.stderr or "")
        return out.strip()
    except Exception as exc:  # pragma: no cover - best effort
        return f"(--help failed: {exc})"


def gen_cli(venv_bin: str | None) -> None:
    venv = Path(venv_bin or (Path.home() / ".venvs/ovos/bin"))
    page = DOCS / "cli-tools.md"
    text = page.read_text()
    commands = sorted(set(CLI_COMMAND_RE.findall(text)))

    blocks = []
    skipped = []
    excluded = []
    for cmd in commands:
        if cmd in UNSAFE_FOR_HELP_CAPTURE:
            excluded.append(cmd)
            continue
        help_text = _capture_help(cmd, venv)
        if help_text is None:
            skipped.append(cmd)
            continue
        blocks.append(f"??? example \"`{cmd} --help`\"\n\n    ```text\n" + "\n".join(
            "    " + line for line in help_text.splitlines()
        ) + "\n    ```")

    body = "\n\n".join(blocks) if blocks else "*(no installed commands captured)*"
    page_text = text
    new_text, found = replace_marked_section(page_text, "cli-help-output", body)
    if not found:
        marker_block = wrap("cli-help-output", body)
        anchor = "\n---\n\n*Source code:"
        if anchor in page_text:
            new_text = page_text.replace(
                anchor,
                f"\n---\n\n## Command `--help` Output (Generated)\n\n{marker_block}\n{anchor}",
                1,
            )
        else:
            new_text = page_text.rstrip() + f"\n\n## Command `--help` Output (Generated)\n\n{marker_block}\n"
    page.write_text(new_text)
    print(f"[cli] captured --help for {len(blocks)}/{len(commands)} documented commands in {page.relative_to(REPO_ROOT)}")
    if skipped:
        print(f"[cli] not installed, skipped: {skipped}")
    if excluded:
        print(f"[cli] excluded (daemon/live-bus command, unsafe to invoke): {excluded}")


# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_wf = sub.add_parser("workflows", help="regenerate gh-automations-workflows.md")
    p_wf.add_argument("--repo-path", default=None, help="local gh-automations clone (default: ~/AgentWorkspaces/ovos/gh-automations)")

    sub.add_parser("config", help="regenerate config-reference.md")

    p_cli = sub.add_parser("cli", help="regenerate cli-tools.md")
    p_cli.add_argument("--venv-bin", default=None, help="venv bin/ dir to look up commands (default: ~/.venvs/ovos/bin)")

    p_all = sub.add_parser("all", help="run all generators")
    p_all.add_argument("--repo-path", default=None)
    p_all.add_argument("--venv-bin", default=None)

    args = ap.parse_args()

    if args.cmd == "workflows":
        gen_workflows(args.repo_path)
    elif args.cmd == "config":
        gen_config()
    elif args.cmd == "cli":
        gen_cli(args.venv_bin)
    elif args.cmd == "all":
        gen_workflows(args.repo_path)
        gen_config()
        gen_cli(args.venv_bin)


if __name__ == "__main__":
    main()
